"""
AtomAI — Code Export Tool
==========================
Exports all core project source files into a single submission_code.txt file.
Run: python export_code.py

Output: submission_code.txt — ready for PDF conversion or code review.
"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
OUTPUT_FILE = PROJECT_ROOT / "submission_code.txt"

# Files to export (relative to project root)
CORE_FILES = [
    "package.json",
    "tsconfig.json",
    "next.config.ts",
    "postcss.config.mjs",
    "src/app/layout.tsx",
    "src/app/page.tsx",
    "src/app/globals.css",
    "src/app/api/chat/route.ts",
    "src/components/AtomViewer.tsx",
    "src/components/AIChat.tsx",
]

# Additional context files (optional — included for completeness)
DOC_FILES = [
    "README.md",
    "project_description.md",
    "demo_script.md",
]

SEPARATOR = "\n" + "=" * 80 + "\n"
SMALL_SEP = "-" * 40


def main() -> None:
    output_parts = []

    # Header
    output_parts.append("AtomAI — Interactive Materials Science Learning Platform")
    output_parts.append("DSH Hacks V1 | AI x STEM Track")
    output_parts.append("Generated by export_code.py")
    output_parts.append(SEPARATOR)

    # Table of contents
    output_parts.append("TABLE OF CONTENTS\n")
    for f in CORE_FILES:
        output_parts.append(f"  [CORE] {f}")
    for f in DOC_FILES:
        output_parts.append(f"  [DOC]  {f}")
    output_parts.append(SEPARATOR)

    # Export core source files
    output_parts.append("CORE SOURCE CODE\n" + SEPARATOR)
    for rel_path in CORE_FILES:
        file_path = PROJECT_ROOT / rel_path
        if file_path.exists():
            output_parts.append(f"// FILE: {rel_path}\n")
            try:
                content = file_path.read_text(encoding="utf-8")
                output_parts.append(content)
            except UnicodeDecodeError:
                output_parts.append("[Binary file skipped]\n")
            output_parts.append(SEPARATOR)
        else:
            output_parts.append(f"// FILE: {rel_path} — NOT FOUND\n")
            output_parts.append(SEPARATOR)

    # Export documentation files
    output_parts.append("PROJECT DOCUMENTATION\n" + SEPARATOR)
    for rel_path in DOC_FILES:
        file_path = PROJECT_ROOT / rel_path
        if file_path.exists():
            output_parts.append(f"-- DOC: {rel_path}\n")
            content = file_path.read_text(encoding="utf-8")
            output_parts.append(content)
            output_parts.append(SEPARATOR)
        else:
            output_parts.append(f"-- DOC: {rel_path} — NOT FOUND\n")
            output_parts.append(SEPARATOR)

    # Footer with stats
    total_content = "".join(output_parts)
    line_count = total_content.count("\n")
    output_parts.append(f"END OF SUBMISSION — {line_count} lines — {len(CORE_FILES)} source files + {len(DOC_FILES)} docs included\n")

    # Write output
    OUTPUT_FILE.write_text("".join(output_parts), encoding="utf-8")
    print(f"[OK] Exported {len(CORE_FILES)} source files + {len(DOC_FILES)} docs")
    print(f"[OK] Output: {OUTPUT_FILE}")
    print(f"[OK] Lines: {line_count}")


if __name__ == "__main__":
    main()
